# This is a basic workflow to help you get started with Actions

name: XRV CI Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'torchxrayvision/**'
      - 'tests/**'
      - 'setup.py'
      - 'requirements*.txt'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'torchxrayvision/**'
      - 'tests/**'
      - 'setup.py'
      - 'requirements*.txt'
      - '.github/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.9']
        torch-version: [2.1.1]
        os: [ubuntu-latest, macos-latest, windows-latest] # only run ubuntu for now because the other ones fail for no reason, macos-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dev dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Install XRV library
      run: |
        pip install -e .

    - name: Install torch version
      run: |
        echo "Installing torch ${{ matrix.torch-version }}"
        python -m pip install torch==${{ matrix.torch-version }} torchvision

    - name: Run tests
      run: pytest
      
